name: phone_number_controller_example
description: "Demonstrates how to use the phone_number_controller plugin."
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  phone_number_controller:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
