name: phone_number_controller
description: "A TextEditingController formatting international phone numbers as you type them."
version: 2.0.0
homepage: https://github.com/QuisApp/phone_number_controller
repository: https://github.com/QuisApp/phone_number_controller

environment:
  sdk: ^3.10.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  phone_numbers_parser: ^9.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
